spring:
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
  application:
    name: ai-coder
  data:
    #redis
    redis:
      host: 1.15.35.203
      port: 26739
      password: mypass123
      ttl: 3600
      user-name: myuser
  sa-token:
    token-name: satoken        # token 名称
    timeout: 2592000            # 有效期，单位秒，默认30天
    is-read-head: true          # 允许从 header 读取 token
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.15.35.203:13306/ai-coder
    username: root
    password: 3r2ZShXsDNY5Nhkk
  profiles:
    active: local
server:
  # cookie 30 天过期
  session:
    cookie:
      max-age: 2592000
  port: 8123
  servlet:
    context-path: /api
# springdoc-aicoder
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.ruizhou.aicoder.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn


